// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quuguxkottzbdjzqherd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dWd1eGtvdHR6YmRqenFoZXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQ1OTMsImV4cCI6MjA2Mzc3MDU5M30.uvkxQxVuPdX9s6eosHdHkZji7e3J3hgBMUDT_57an5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);